[package]
name = "faction_enlistment"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "faction_enlistment"

[features]
prod = []
no-entrypoint = []
no-idl = []
cpi = ["no-entrypoint"]
default = ["no-idl"]

[dependencies]
star_frame = { path = "../../star_frame" }
bytemuck.workspace = true

[dev-dependencies]
solana-program-test.workspace = true
solana-sdk.workspace = true
solana-transaction-status.workspace = true
solana-client.workspace = true
tokio.workspace = true
rand.workspace = true
