name: Publish

on:
  workflow_call:
    secrets:
      CRATES_IO_TOKEN:
        required: true
  workflow_dispatch:

permissions:
  contents: write

defaults:
  run:
    shell: bash

jobs:
  publish-crates:
    runs-on: warp-ubuntu-latest-x64-32x
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache-provider: 'warpbuild'

      - name: Add cargo-release
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-release@0.25.17

      - name: Configure Actions Bot
        uses: ./.github/actions/configure-actions-bot

      - name: Log in to Cargo
        run: cargo login ${{ secrets.CRATES_IO_TOKEN }}

      - name: Run cargo release
        run: cargo release --allow-branch 'main' --no-confirm --no-tag --unpublished -x

      - id: version
        uses: ./.github/actions/detect-version

      - uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          make_latest: true
          name: Release v${{ steps.version.outputs.version }}
          tag_name: v${{ steps.version.outputs.version }}
